Added get executions to flytectl Usage : 1] Returns list of executions in a project domain
bin/flytectl get executions  -d development  -p flytesnacks
INFO[0000] Using config file: [config.yaml]
INFO[0000] Config section [adminutils] updated. No update handler registered.  src="viper.go:318"
INFO[0000] Config section [logger] updated. Firing updated event.  src="viper.go:320"
| NAME (4)   | WORKFLOW NAME                                                      | TYPE     | PHASE     | STARTED                        | ELAPSED TIME  |
 ------------ -------------------------------------------------------------------- ---------- ----------- -------------------------------- ---------------
| h5i7q5h9he | recipes.07_juptyer_notebooks.whole_square_workflow.whole_square_wf | WORKFLOW | SUCCEEDED | 2021-01-19T10:42:41.467046Z    | 62.763573800s |
| lqi9q9l8fb | recipes.07_juptyer_notebooks.whole_square_workflow.whole_square_wf | WORKFLOW | ABORTED   | 2021-01-19T10:48:12.546933900Z | 13.067154500s |
| vcfy9487ud | recipes.07_juptyer_notebooks.whole_square_workflow.whole_square_wf | WORKFLOW | ABORTED   | 2021-01-20T04:28:08.272178800Z | 8.317607300s  |
| zgxdehv84b | recipes.07_juptyer_notebooks.whole_square_workflow.whole_square_wf | WORKFLOW | ABORTED   | 2021-01-19T15:34:38.757407800Z | 18.213011300s |
4 rows

2] Returns a single execution based on its NAME ($.id.name)
bin/flytectl get executions  h5i7q5h9he -d development  -p flytesnacks
INFO[0000] Using config file: [config.yaml]
INFO[0000] Config section [admin] updated. Firing updated event.  src="viper.go:320"
INFO[0000] Config section [adminutils] updated. No update handler registered.  src="viper.go:318"
INFO[0000] Config section [logger] updated. Firing updated event.  src="viper.go:320"
| NAME       | WORKFLOW NAME                                                      | TYPE     | PHASE     | STARTED                     | ELAPSED TIME  |
 ------------ -------------------------------------------------------------------- ---------- ----------- ----------------------------- ---------------
| h5i7q5h9he | recipes.07_juptyer_notebooks.whole_square_workflow.whole_square_wf | WORKFLOW | SUCCEEDED | 2021-01-19T10:42:41.467046Z | 62.763573800s |
1 rows

3] For an invalid name it currently prints the error and display help
and panic trace. This needs to be enhanced to not show the trace if its
user error

bin/flytectl get executions  WORKFLOW -d development  -p flytesnacks
INFO[0000] Using config file: [config.yaml]
INFO[0000] Config section [logger] updated. Firing updated event.  src="viper.go:320"
Error: rpc error: code = NotFound desc = entry not found
Usage:
   get execution [flags]

Aliases:
  execution, executions

Flags:
  -h, --help   help for execution

Global Flags:
      --admin.authorizationHeader string      Custom metadata header to pass JWT
      --admin.authorizationServerUrl string   This is the URL to your IDP's authorization server'
      --admin.clientId string                 Client ID
      --admin.clientSecretLocation string     File containing the client secret
      --admin.endpoint string                 For admin types,  specify where the uri of the service is located.
      --admin.insecure                        Use insecure connection.
      --admin.maxBackoffDelay string          Max delay for grpc backoff (default "8s")
      --admin.maxRetries int                  Max number of gRPC retries (default 4)
      --admin.perRetryTimeout string          gRPC per retry timeout (default "15s")
      --admin.scopes strings                  List of scopes to request
      --admin.tokenUrl string                 Your IDPs token endpoint
      --admin.useAuth                         Whether or not to try to authenticate with options below
      --adminutils.batchSize int              Maximum number of records to retrieve per call. (default 100)
      --adminutils.maxRecords int             Maximum number of records to retrieve. (default 500)
      --config string                         config file (default is $HOME/config.yaml)
  -d, --domain string                         Specifies the Flyte project's domain.
      --logger.formatter.type string          Sets logging format type. (default "json")
      --logger.level int                      Sets the minimum logging level. (default 4)
      --logger.mute                           Mutes all logs regardless of severity. Intended for benchmarks/tests only.
      --logger.show-source                    Includes source code location in logs.
  -o, --output string                         Specifies the output type - supported formats [TABLE JSON YAML] (default "TABLE")
  -p, --project string                        Specifies the Flyte project.
      --root.domain string                    Specified the domain to work on.
      --root.output string                    Specified the output type.
      --root.project string                   Specifies the project to work on.

panic: rpc error: code = NotFound desc = entry not found

goroutine 1 [running]:
main.main()
	/Users/pmahindrakar/flyte-complete/flytectl/main.go:7 +0x47